# Generated by Django 5.2.1 on 2025-05-14 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('trawiasty', 'Trawiasty'), ('mączka', 'Mączka'), ('twardy', 'Twardy'), ('dywanowy', 'Dywanowy')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lokalizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=255)),
                ('kod_pocztowy', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='GodzinyOtwarcia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzien_tygodnia', models.CharField(max_length=20)),
                ('godzina_otwarcia', models.TimeField()),
                ('godzina_zamkniecia', models.TimeField()),
                ('kort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korty.kort')),
            ],
        ),
        migrations.AddField(
            model_name='kort',
            name='lokalizacja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korty.lokalizacja'),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=9, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('godzina', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('kort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korty.kort')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korty.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Wydarzenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('uczestnicy', models.ManyToManyField(to='korty.profil')),
            ],
        ),
    ]
