# Generated by Django 5.2.1 on 2025-05-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='godzinyotwarcia',
            options={'verbose_name_plural': 'Godziny Otwarcia'},
        ),
        migrations.AlterModelOptions(
            name='kort',
            options={'verbose_name_plural': 'Kort'},
        ),
        migrations.AlterModelOptions(
            name='lokalizacja',
            options={'verbose_name_plural': 'Lokalizacja'},
        ),
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name_plural': 'Profil'},
        ),
        migrations.AlterModelOptions(
            name='rezerwacja',
            options={'verbose_name_plural': 'Rezerwacja'},
        ),
        migrations.AlterModelOptions(
            name='wydarzenia',
            options={'verbose_name_plural': 'Wydarzenia'},
        ),
        migrations.AddField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
