# Generated by Django 5.2.1 on 2025-05-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korty', '0002_alter_godzinyotwarcia_options_alter_kort_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatary/'),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='status',
            field=models.CharField(choices=[('wolne', 'Wolne'), ('zajęte', 'Zajęte')], default='wolne', editable=False, max_length=20),
        ),
    ]
