# Generated by Django 5.2.1 on 2025-05-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korty', '0003_alter_profil_avatar_alter_rezerwacja_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerwacja',
            name='godzina',
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='godzina_koniec',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='godzina_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='status',
            field=models.CharField(choices=[('wolne', 'Wolne'), ('zajete', 'Zajęte')], default='wolne', editable=False, max_length=20),
        ),
    ]
