# Generated by Django 5.2.1 on 2025-05-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korty', '0004_remove_rezerwacja_godzina_rezerwacja_godzina_koniec_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezerwacja',
            options={'verbose_name_plural': 'Rezerwacje'},
        ),
    ]
